---
# all commands by default will run on every commit
default_install_hook_types: [pre-commit]
default_stages: [commit]
# some configs are only available after v2.18
minimum_pre_commit_version: '2.18'
repos:
    # Git hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: no-commit-to-branch # prevents users from pushing changes to specific (protected) branches
            args: [--branch, develop, --branch, main]
            name: Git checks - prevent pushing to protected branches
    - repo: local
      hooks:
          - id: git_branch_name_validation # Custom Git branch validation hook
            name: Git checks - validate branch name
            description: This hook validates the Git branch name.
            entry: src/sh/pre_commit_hook_validate_git_branch_name.sh
            language: script
            pass_filenames: false
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-merge-conflict # checks for files that contain merge conflict strings.
            name: Git checks - detect merge conflicts
    # YAML hooks
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.30.0
      hooks:
          - id: yamllint # Lint YAML files using rules specified in .yamllint
            args: [-c=.yamllint]
            name: YAML checks - YAML linting with yamllint
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt # yamlfmt - fix input yaml files
            name: YAML fixes - fix YAML formatting

    # Python - fixes
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.2
      hooks:
          - id: ruff
            args: [--line-length=120]
            name: Python fixes - format Python code using Ruff

    # Python - checks
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
          - id: flake8 # enforces flake8 style consistency across Python files.
            language_version: python3
            args: [--max-line-length=120, --max-complexity=10]
            name: Python checks - lint Python code with Flake8

    - repo: local
      hooks:
          - id: pytest-check
            name: Python checks - pytest
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: name-tests-test # verifies Python test files are named correctly - i.e., ensure py tests match /test*.py
            args: [--pytest-test-first]
            name: Python checks - pytest - ensure standard Pytest naming
    - repo: https://github.com/pycqa/bandit
      rev: 1.8.3
      hooks:
          - id: bandit # Perform security checks with bandit
            name: Python checks - Bandit - security checks
            args: [--severity, medium]
    # General/housekeeping hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
            name: General fixes - check file endings
          - id: trailing-whitespace # trims trailing whitespace.
            name: General fixes - remove trailing whitespace
          - id: fix-byte-order-marker # removes utf-8 byte order marker.
            name: General fixes - remove UTF-8 byte order marker (BOM)
          - id: mixed-line-ending # replaces or checks mixed line ending.
            name: General fixes - normalise line endings
          - id: check-added-large-files # prevents giant files from being committed.
            name: General checks - check for large files
          - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
            name: General checks - check string case conflicts
          - id: detect-private-key # checks for the existence of private keys.
            name: General checks - detect private keys
