run_py_test:
	pytest -rA tests/test_cases.py --no-header

pytestconfig_eg:
	pytest tests/test_dag_validation.py --dag_name example_dag


TODO_good_pytest_optns:
	# e.g., --disable-pytest-warnings -v -q
